### ISSUE TITLE
eslint fails for npm run build

### ISSUE THREAD

**Issue by renrut** [aws-solutions/scalable-analytics-using-apache-druid-on-aws#6]
**Describe the bug**
Thanks for this! It's very helpful for prototyping with Druid on fargate!

`npm run build` can result in a bunch of parsing errors on the .ts files such as 
```
  17:1  error  Parsing error: The keyword 'import' is reserved
```

This happened on my mac.

**To Reproduce**
```
git clone
<update cdk.json> (I used the quickstart.small/cdk.json.eks_fargate)
cd source
npm install
npm run build or npm run lint
```

**Expected behavior**
npm run lint succeeds

**Please complete the following information about the solution:**
- n/a pre-deployment

**Solution**

Creating `.eslintrc.js` file in source directory with the following seemed to work for me...
```
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: ['tsconfig.json'],
  },
  plugins: ['@typescript-eslint'],
  extends: ['plugin:@typescript-eslint/recommended', 'prettier'],
  // For the list of rules supported by @typescript-eslint/eslint-plugin,
  // see: https://typescript-eslint.io/rules/
  rules: {
    '@typescript-eslint/no-unused-vars': 'error',
  },
};
```

**Comment by van-vothanh** [comment]
Hi @renrut,

Thank you for letting us know about the issue and for providing a workaround! I've added the missing `.eslintrc.js` file to the repo, please retry and let us know if it works for you.

Cheers

Van
